# Generated by Django 5.1.4 on 2024-12-09 18:11

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("due", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
