# Generated by Django 5.1.4 on 2024-12-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="flashcard",
            table=None,
        ),
    ]
