# Generated by Django 5.1.4 on 2025-01-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_alter_flashcard_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="current_interval",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="ease_factor",
            field=models.FloatField(default=2.5),
        ),
    ]
