# Generated by Django 5.1.4 on 2025-01-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_flashcard_current_interval_flashcard_ease_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="history",
            field=models.JSONField(default=list),
        ),
    ]
