# Generated by Django 5.1.4 on 2025-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0004_flashcard_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="ease_factor",
            field=models.FloatField(default=1.5),
        ),
    ]
