# Generated by Django 5.1.4 on 2025-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0006_userplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("free", "free"),
                    ("pro", "pro"),
                    ("enterprise", "enterprise"),
                ],
                default="free",
                max_length=50,
            ),
        ),
    ]
