# Generated by Django 5.1.4 on 2025-01-27 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0007_alter_userplan_plan_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplan",
            name="total_tokens_allowed",
            field=models.IntegerField(default=10000),
        ),
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens_used", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("context", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "token_usage",
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="token_usage_user_id_dd3fa1_idx",
                    )
                ],
            },
        ),
    ]
