# Generated by Django 5.1.4 on 2025-01-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0008_alter_userplan_total_tokens_allowed_tokenusage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenusage",
            name="context",
        ),
    ]
