# Generated by Django 5.1.4 on 2025-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0009_remove_tokenusage_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("feedback_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
