# Generated by Django 5.1.4 on 2025-02-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0010_failedfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="failedfeedback",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
