# Generated by Django 5.1.4 on 2025-02-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0012_testuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestUser",
        ),
    ]
