# Generated by Django 5.1.4 on 2025-02-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0014_userdocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="title",
        ),
    ]
