# Generated by Django 5.1.4 on 2025-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0015_remove_userdocument_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="name",
            field=models.CharField(default="unnamed", max_length=255),
            preserve_default=False,
        ),
    ]
