# Generated by Django 5.1.4 on 2025-02-27 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0016_userdocument_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="bounding_box",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flashcards",
                to="flashcards.userdocument",
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
