# Generated by Django 5.1.4 on 2025-03-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0017_flashcard_bounding_box_flashcard_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="bounding_box",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="flashcards.deck",
            ),
        ),
    ]
