# Generated by Django 5.1.4 on 2025-04-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0018_alter_flashcard_bounding_box_alter_flashcard_deck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="page_number",
        ),
    ]
