# Generated by Django 5.1.4 on 2025-04-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0019_remove_flashcard_page_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
