# Generated by Django 5.1.4 on 2025-04-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0020_flashcard_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcards",
                to="flashcards.deck",
            ),
        ),
    ]
