# Generated by Django 5.1.4 on 2025-04-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0021_alter_flashcard_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="deck",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="flashcards.deck",
            ),
        ),
    ]
