# Generated by Django 5.1.4 on 2025-04-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0022_userdocument_deck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdocument",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="flashcards.deck",
            ),
        ),
    ]
