# Generated by Django 5.1.4 on 2025-06-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0023_alter_userdocument_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="file_size",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flashcard",
            name="accepted",
            field=models.BooleanField(default=True),
        ),
    ]
